### ISSUE TITLE
change cd git to cd blog.jboss-outreach.org  content setup for linux

### ISSUE THREAD

**Issue by avsingh999** [JBossOutreach/blog.jboss-outreach.org#124]
In this page https://blog.jboss-outreach.org/support/setup-linux there is  setup of this project but 
here is mistake after clone git repository we have to  'cd blog.jboss-outreach.org'  this

![jbioss3](https://user-images.githubusercontent.com/25536022/46191803-74bc6280-c316-11e8-8c67-334fef3ff82b.png)

**Comment by alirizwi** [comment]
Can I work on this issue?

**Comment by avsingh999** [comment]
@alirizwi sorry but  I want

**Comment by alirizwi** [comment]
@avsingh999 Sure, there is a similar issue for setup in eclipse-che instructions. I am working on that

**Comment by alirizwi** [comment]
@avsingh999 If you are not working on this, I will solve this.
